swagger: '2.0'
info: 
  title: Customer
  description: The eFile replacement Customer information REST API
  version: ""
host: 'eservices-test-gateway.npnsp.ird.govt.nz'
basePath: /secure/gateway/customer/
schemes: 
  - https
paths: 
  /customer: 
    post: 
      tags: 
        - Customer Retrieve
      summary: Customer Retrieve
      description: ""
      operationId: customerPOST
      consumes: 
        - 'application/json; charset=utf-8'
      produces: 
        - 'application/json; charset=utf-8'
      parameters: 
        - name: body
          in: body
          required: true
          schema: 
            $ref: '#/definitions/customer_POST_Request'
      responses: 
        '200': 
          description: 'HttpStatus: 200 - OK'
          schema: 
            $ref: '#/definitions/customer_POST_Response200'
        '400': 
          description: 'HttpStatus: 400 - BadRequest'
          schema: 
            $ref: '#/definitions/customer_POST_Response400'
        '500': 
          description: 'HttpStatus: 500 - InternalServerError'
          schema: 
            $ref: '#/definitions/customer_POST_Response500'
        default: 
          description: ' '
          schema: 
            $ref: '#/definitions/customer_POST_ResponseDefault'
definitions: 
  customer_POST_Request: 
    type: object
    required: 
      - CustomerID
      - CustomerIDType
    properties: 
      CustomerID: 
        type: string
        description: '<p>The unique identifier of a customer that can be retrieved through the customer information service.</p>'
      CustomerIDType: 
        type: string
        description: '<p>The type of unique identifier of a customer that can be retrieved through the customer information service.</p>'
  customer_POST_Response200: 
    type: object
    required: 
      - Customer
    properties: 
      Customer: 
        type: object
        required: 
          - ID
          - IDType
          - EntityType
          - Commence
          - Name
        properties: 
          ID: 
            type: string
            description: '<p>The unique identifier of a customer that can be retrieved through the customer information service.</p>'
          IDType: 
            type: string
            description: '<p>The type of unique identifier of a customer that can be retrieved through the customer information service.</p>'
          EntityType: 
            type: string
            description: '<p>The entity type of the customer.</p>'
          EntitySubType: 
            type: string
            description: '<p>The entity sub type of the customer.</p>'
          Commence: 
            type: string
            description: '<p>The date the customer was registered.</p>'
          Cease: 
            type: string
            description: '<p>The date the customer ceased operating, or 9999-12-31 if customer has not ceased.</p>'
          NZBN: 
            type: string
            description: '<p>The New Zealand Business Number of the customer, if one is known.</p>'
          BIC: 
            type: array
            items: 
              type: object
              required: 
                - BICCode
              properties: 
                BICCode: 
                  type: string
                  description: '<p>A Business Industry Classification Code associated to the customer.</p>'
          Address: 
            type: array
            items: 
              type: object
              required: 
                - AddressID
                - Type
                - Formatted
                - PostCode
                - Country
                - Attention
                - Urbanisation
                - Municipality
                - District
                - SubDistrict
                - SubProvince
                - Updated
              properties: 
                AddressID: 
                  type: number
                  format: int64
                  description: '<p>The unique identifier of an address. This is required when updating or deleting an address.</p>'
                Type: 
                  type: string
                  description: '<p>The unique identifier of an address. This is required when updating or deleting an address.</p>'
                Formatted: 
                  type: string
                  description: '<p>The full address formatted into a single string.</p>'
                Street: 
                  type: string
                  description: '<p>The first street line of the address.</p>'
                Street2: 
                  type: string
                  description: '<p>The second street line of the address.</p>'
                Unit: 
                  type: string
                  description: '<p>The unit of the address.</p>'
                UnitType: 
                  type: string
                  description: '<p>The unit type of the address.</p>'
                City: 
                  type: string
                  description: '<p>The city of the address.</p>'
                State: 
                  type: string
                  description: '<p>The state of the address. Represented as the ISO 3166-2 subdivision</p>'
                PostCode: 
                  type: string
                  description: '<p>The post code of the address.</p>'
                Country: 
                  type: string
                  description: '<p>The ISO 3166-1 alpha-2 country code of the address.</p>'
                Attention: 
                  type: string
                  description: '<p>The person to whom the correspondence is addressed.</p>'
                Urbanisation: 
                  type: string
                  description: '<p>The person to whom the correspondence is addressed.</p>'
                Municipality: 
                  type: string
                  description: '<p>The person to whom the correspondence is addressed.</p>'
                District: 
                  type: string
                  description: '<p>The district of the address.</p>'
                SubDistrict: 
                  type: string
                  description: '<p>The sub district of the address.</p>'
                SubProvince: 
                  type: string
                  description: '<p>The sub province of the address.</p>'
                Updated: 
                  type: string
                  description: '<p>The date that the address was last updated.</p>'
          Name: 
            type: array
            items: 
              type: object
              required: 
                - NameID
                - Type
                - Formatted
                - Updated
              properties: 
                NameID: 
                  type: number
                  format: int64
                  description: '<p>The unique identifier of a name. This is required when updating or deleting a name.</p>'
                Type: 
                  type: string
                  description: '<p>The type of name.</p>'
                Formatted: 
                  type: string
                  description: '<p>The full name formatted into a single string. For non individuals, this is the only name.</p>'
                LastName: 
                  type: string
                  description: '<p>The last name or surname of an individual.</p>'
                MiddleName: 
                  type: string
                  description: '<p>The middle name of an individual.</p>'
                FirstName: 
                  type: string
                  description: '<p>The first name of an individual.</p>'
                Title: 
                  type: string
                  description: '<p>The title of an individual.</p>'
                Suffix: 
                  type: string
                  description: '<p>The suffix of an individual.</p>'
                Updated: 
                  type: string
                  description: '<p>The date that the name was last updated.</p>'
          Contact: 
            type: array
            items: 
              type: object
              required: 
                - ContactID
                - ContactType
                - Name
                - Updated
              properties: 
                ContactID: 
                  type: number
                  format: int64
                  description: '<p>The unique identifier of a contact for the customer. This is required when updating or deleting a contact.</p>'
                ContactType: 
                  type: string
                  description: '<p>The type of contact.</p>'
                Name: 
                  type: string
                Updated: 
                  type: string
                  description: '<p>The date that the contact was last updated.</p>'
                Phone: 
                  type: array
                  items: 
                    type: object
                    required: 
                      - PhoneID
                      - PhoneType
                      - Country
                    properties: 
                      PhoneID: 
                        type: number
                        format: int64
                        description: '<p>The unique identifier of a phone number. This is required when updating or deleting a phone number.</p>'
                      PhoneType: 
                        type: string
                        description: '<p>The type of phone.</p>'
                      Country: 
                        type: string
                        description: '<p>The ISO 3166-1 alpha-2 country code indicating the country for the phone number.</p>'
                      AreaCode: 
                        type: string
                        description: '<p>The area code of the phone number.</p>'
                      PhoneNumber: 
                        type: string
                        description: '<p>The phone number, without country code.</p>'
                      Extension: 
                        type: string
                        description: '<p>The extension of the phone number.</p>'
  customer_POST_Response400: 
    type: object
    required: 
      - errors
    properties: 
      errors: 
        type: array
        description: Validation array
        items: 
          type: object
          description: Errors Object
          required: 
            - code
            - type
            - message
          properties: 
            code: 
              type: string
              description: 'Error code for validation, security, or server type responses.<br><br><table><tbody><tr><th>code</th><th>description</th></tr><tr><td>EV1020</td><td>Authentication failure means the token (JWT or OAuth) provided is not valid</td></tr><tr><td>EV1021</td><td>No OAuth or JWT token is present as an HTTP header</td></tr><tr><td>EV1022</td><td>Access is not permitted for the requester to perform this operation for the submitted identifier</td></tr><tr><td>EV1100</td><td>Invalid input parameters. Please check documentation</td></tr></tbody></table>'
              maxLength: 6
              enum: 
                - EV1020
                - EV1021
                - EV1022
                - EV1100
            type: 
              type: string
              description: Type of validation code returned
              enum: 
                - result
                - security
                - server
                - validation
            message: 
              type: string
              description: Error Message
  customer_POST_Response500: 
    type: object
    required: 
      - errors
    properties: 
      errors: 
        type: array
        description: Validation array
        items: 
          type: object
          description: Errors Object
          required: 
            - code
            - type
            - message
          properties: 
            code: 
              type: string
              description: 'Error code for validation, security, or server type responses.<br><br><table><tbody><tr><th>code</th><th>description</th></tr><tr><td>EU6001</td><td>Unexpected error occurred</td></tr></tbody></table>'
              maxLength: 6
              enum: 
                - EU6001
            type: 
              type: string
              description: Type of validation code returned
              enum: 
                - result
                - security
                - server
                - validation
            message: 
              type: string
              description: Error Message
  customer_POST_ResponseDefault: 
    type: object
    required: 
      - errors
    properties: 
      errors: 
        type: array
        description: Validation array
        items: 
          type: object
          description: Errors Object
          required: 
            - code
            - type
            - message
          properties: 
            code: 
              type: string
              description: 'Error code for validation, security, or server type responses.<br><br><table><tbody><tr><th>code</th><th>description</th></tr><tr><td>EV1020</td><td>Authentication failure means the token (JWT or OAuth) provided is not valid</td></tr><tr><td>EV1021</td><td>No OAuth or JWT token is present as an HTTP header</td></tr><tr><td>EV1022</td><td>Access is not permitted for the requester to perform this operation for the submitted identifier</td></tr><tr><td>EV1100</td><td>Invalid input parameters. Please check documentation</td></tr></tbody></table>'
              maxLength: 6
              enum: 
                - EV1020
                - EV1021
                - EV1022
                - EV1100
            type: 
              type: string
              description: Type of validation code returned
              enum: 
                - result
                - security
                - server
                - validation
            message: 
              type: string
              description: Error Message